### PR TITLE
Updated react dependency version to ^18.2.0

### PR DESCRIPTION
**Pull request by JosefRousal**
Simple update to allow react v18 support.

### CODE REVIEW

**Comment by alexandrughinea** [comment]
Any plans to get this merged soon?
Many thanks

**Comment by awkaiser-tr** [comment]
Hi @JosefRousal @alexandrughinea, just opened #13 which I believe is a cleaner resolution to the problem 🙇🏻

**Comment by Lukem121** [comment]
Here is a fork of the project that works with React 18
npm install formik-adapter-zod

**Comment by robertLichtnow** [comment]
React peer dependency was removed in [v1.2.0](https://www.npmjs.com/package/zod-formik-adapter/v/1.2.0)

**Pull request closed without merging**
